### ISSUE TITLE
paccup_overlay.py spams Invalid dfWestLongitudeDeg error

### ISSUE THREAD

**Issue by rkaiser0324** [lanceberc/ycwx#7]
Running the script yields this repeated error:

![image](https://user-images.githubusercontent.com/1090569/205464831-abbcecc7-87b7-476d-9b2c-702bfff0ccda.png)

**Comment by lanceberc** [comment]
Yes, it might be because the warp crosses the anitmeridian. I haven't found GDAL to be particularly scrutible.

**Comment by lanceberc** [comment]
Also, the call to warp causes gdal to emit a "sidecar" file that is removed by paccup_overlay.py. Telling gdal to not emit sidecars causes warp to fail.

At one point reprojection was implemented with cartopy instead of gdal but it was much slower and used far more memory. See https://github.com/lanceberc/GOES/blob/master/GOES_Cartopy.ipynb.

**Comment by rkaiser0324** [comment]
If it doesn't have any practical effect this error should probably be caught and suppressed.

**Comment by lanceberc** [comment]
It sure would be nice if GDAL raised an exception, but it doesn't. It doesn't hurt anything and doesn't affect correctness.

**Comment by rkaiser0324** [comment]
Ok closing.
